### ISSUE TITLE
Doesn't write properly sometimes

### ISSUE THREAD

**Issue by Cysign** [thijse/Arduino-EEPROMEx#7]
Hey guys,
I'm using this library in a project and figured out that it doesn't always save data to EEPROM properly.
In general this library works great, but sometimes there's no write/update made where it should.

In my project I'm using the following librarys:
sdelay.h
Wire.h 
OneWire.h
DallasTemperature.h
LiquidCrystal_I2C.h
EEPROMex.h
Time.h
DS1307RTC.h

How can I figure out which version of EEPROMex I'm using?
My EEPROMex-folder is named "EEPROMEx-9.1"...but I can't remember if this was the default folder name or I changed it.

**Comment by per1234** [comment]
The problem is that the author has the library in debug mode by default so the max number of writes is 100. If you still need debug output you can change the _allowedWrites value using setMaxAllowedWrites() or if you don't need debug output you should comment out line 30 of EEPROMex.cpp to reduce memory usage and make EEPROMex run faster. I submitted https://github.com/thijse/Arduino-EEPROMEx/pull/3 to disable debug mode by default a couple months ago.

**Comment by Cysign** [comment]
Is max. No of writes once per uploaded sketch or once the circuit is powered?
That might fix my issues. I'll check this, thanks!

**Comment by per1234** [comment]
Per each time the circuit is powered on or the MCU is reset. Note this is the total number of EEPROM writes, not the number of writes to an EEPROM address.

**Comment by Cysign** [comment]
Any chance I could disable debug in my code instead ot the EEPROMex.cpp file?

**Comment by per1234** [comment]
No way I know of to do this with the way the library is currently written. The new stock Arduino EEPROM library actually does almost everything EEPROMex does except for getAddress() and I wrote [a library](https://github.com/per1234/EEPROMallocation) that does that separately.

**Comment by Cysign** [comment]
Thanks for your support!
